### ISSUE TITLE
Opening the start menu with keyboard shortcut (Alt F1) does not change input focus

### ISSUE THREAD

**Issue by michel-slm** [evolve-os/budgie-desktop#108]
If I open the start menu with the keyboard shortcut, the input focus remains unchanged (e.g. I'm typing this bug entry now, pressed Alt-F1 and I could still continue typing in the text box).

If I click on the start menu button, however, input focus switches correctly to the search text box on the start menu itself.

     rpm -q budgie-desktop
    budgie-desktop-8-1.1.x86_64

**Comment by Justinzobel** [comment]
This has been fixed in a recent commit and will be updated into the package when possible.

**Comment by ikeydoherty** [comment]
Aha, this was the bug! Cheers @Justinzobel was looking for this one last night :D Yeah, this got fixed early hours of this morning, woo ! :D

**Comment by codeRSH** [comment]
I am still not able to open the Budgie Menu applet using Alt-F1. 

On pressing Alt-F1 the menu applet button gets highlighted, but it doesn't open. Please help. I am using Budgie Desktop 10.4

**Comment by cazacugmihai** [comment]
I have the same issue as @codeRSH on `budgie-desktop 10.4`.
